name = "my-d1-project"
main = "workers.js"
compatibility_date = "2026-05-21"

[[d1_databases]]
binding = "DB"
database_name = "mydatabase"
database_id = "e8919e29-fb17-4ac4-a5d9-9e6e0e08a9c4"
